### ISSUE TITLE
We would really like to invite you for a technology live about DynaMem

### ISSUE THREAD

**Issue by autodriving-heart** [hello-robot/stretch_ai#215]
Hi, we are the team of *_*Embodied-Intelligence-Heart**_. Admired of your extremely impressive achievement, we would like to invite you to share your achievements on our platform!

Currently, we have accumulated a large number of fans in the fields of autonomous driving and embodied AI. They are distributed in over well-known 300 companies and laboratories both domestically and internationally. We have held over 100 open-source sharing sessions in the past two years. We sincerely hope to invite your team to join in a live broadcast. Look forward to your reply!

**WeChat: AIDriver002**
![111](https://github.com/user-attachments/assets/dabf5a92-7172-43e5-adb9-0c1d464780d3)

**Comment by hello-cpaxton** [comment]
Hey, @hello-peiqi  will follow up abotu this, thank you for your interest!
